### ISSUE TITLE
[10.0] password_security: Should be allowed users creation to erp manager

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/server-tools#100]
Explaination
-----------------

Currently exist a restriction that deny users creation to users different to root user (Administrator), this restriction was made specifically to avoid password change to a user different to enviroment user.

![unnamed 1](https://cloud.githubusercontent.com/assets/5335402/25720538/de26d3f4-30d2-11e7-85db-06196a3b8049.png)

The proposal to solve that, is create a rule that allow create `res.user.pass.history` to users in group _Administration / Access Rights_

**Comment by luisg123v** [comment]
@suniagajose 
Could you close this issue, please? It's been already solved on https://github.com/Vauxoo/server-tools/pull/101

**Comment by suniagajose** [comment]
merged in #101
