### ISSUE TITLE
[RFC] odoolint: Check if a original name of parameter is modified

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/server-tools#102]
Review the following cases:
 - https://github.com/odoo/enterprise/pull/839

**Comment by JesusZapata** [comment]
@moylop260 
I can't see the odoo/enterprise repository 
![image](https://user-images.githubusercontent.com/1387970/26898706-e3b4965c-4b9a-11e7-9dbd-35c5150b1151.png)

**Comment by moylop260** [comment]
The original value of the method inherited is called `values` but someone have defined the inherited method `qwebcontext`
![screen shot 2017-06-09 at 10 09 24](https://user-images.githubusercontent.com/6644187/26981209-04e7e576-4cfa-11e7-959c-d406f5a685b5.png)
