### ISSUE TITLE
[RFC] odoolint: Check if a models is inherited for TransientModel for a Model

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/server-tools#112]
Currently odoo don't emit a error if you use:

```python
class ClassA(model.Models):
   _name='class.a'
...
class ClassB(model.TrasientModels):
   _inherit='class.a'
```

Notice that the inherited class use TransientModels but original one uses model.Models.

**Comment by luisg123v** [comment]
This is natively covered from a long time ago, see https://github.com/odoo/odoo/commit/4ee6adf4b2371
