### ISSUE TITLE
mass editing v11 broken.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/server-tools#133]
Creating a rule this error appears on the m2m fiels when you will add a field.

![image](https://user-images.githubusercontent.com/338634/33155797-31385ae2-cfb9-11e7-881a-4331991f14a1.png)

**Comment by luisg123v** [comment]
@moylop260 
Could we close this issue?

- It's already solved on https://github.com/Vauxoo/server-tools/pull/134 AFAIC
- `mass_editing` no longer belongs to this project
