### ISSUE TITLE
Remove duplicated modules present in other projects

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/server-tools#139]
As mentioned in the OCA's server-tools migration issue (https://github.com/OCA/server-tools/issues/1008), there are some modules that no longer belong to this project and they were moved to other projects.

For instance, the module `password_security` [is still in this project](https://github.com/Vauxoo/server-tools/tree/11.0/password_security) but it's also in [the `server-auth` project](https://github.com/Vauxoo/server-auth/tree/11.0/password_security).

There are several modules that, like in the above case, are duplicated and should be removed from here IMO.

**Comment by luisg123v** [comment]
CC @moylop260

**Comment by moylop260** [comment]
+1
