### ISSUE TITLE
[webhook] Add links to oficial doc of how to create a module

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/server-tools#5]
`Te quedó perfecta la doc (yo agregaría links a la doc oficial de como crear el módulo y la parte de la clase y todo el cuento pero creo que el código habla por si solo).`

**Comment by moylop260** [comment]
@nhomar 
I don't understand it

**Comment by nhomar** [comment]
@moylop260 It is just change a little the redation and some typos and add some links I'll do it and I make a PR.
